site_name: Technical Writing with mkdocs

use_directory_urls: true
docs_dir: docs

nav:
  - Home: index.md
  - Why mkdocs?: why.md
  - Setup and Configuration: config.md
  - "Solved: Distributed Navigation": nav.md
  - "Solved: Link Checking": link.md

theme:
  name: 'material'
  logo: 'favicon.ico'
  favicon: 'favicon.ico'

extra_css:
    - 'stylesheets/hal.css'

markdown_extensions:
    - admonition
    - mkdcomments
    - markdown_include.include
    - codehilite
    - toc:
        permalink: True



