site_name: Technical Writing with mkdocs

use_directory_urls: true
docs_dir: docs

nav:
  - Home: index.md

theme:
  name: 'material'
  font:
    text: Compasse
  logo: 'favicon.ico'
  favicon: 'favicon.ico'

extra_css:
    - 'stylesheets/hal.css'

markdown_extensions:
    - admonition
    - mkdcomments
    - markdown_include.include
    - codehilite
    - toc:
        permalink: True



