---
swagger: "2.0"
info:
  x-api-id: e8f3e86d-e364-456e-80b6-9b7f366b9acf
  version: "0.1-draft"
  title: "Events API"
  description: |
    This is the events API that allows internal services to create and read events using access_token
host: api.etrusted.com
schemes:
- "https"
securityDefinitions:
  apiKey:
    type: "apiKey"
    name: "Authorization"
    in: "header"
paths:
  /events:
    post:
      summary: "Create new event"
      tags:
        - Events
      security:
        - apiKey: []
      description: This API creates new events
      consumes:
        - "application/json"
      produces:
        - "application/json"
      parameters:
      - in: body
        name: body
        schema:
          $ref: "#/definitions/eventBody"
      responses:
        202:
          description: "202 response"
          schema:
            $ref: "#/definitions/eventPostResponse"
        400:
          description: "400 Bad Request"
          schema:
            $ref: "#/definitions/eventPostValidationErrorResponse"
        401:
          description: "Unauthorized"
          schema:
            $ref: '#/definitions/UnauthorizedError'
  /events/{eventRef}:
    get:
      summary: "Get event"
      tags:
        - Events
      security:
        - apiKey: []
      description: This API retrieves events by id
      produces:
        - "application/json"
      parameters:
        - name: eventRef
          in: path
          required: true
          type: string
      responses:
        200:
          description: OK
          schema:
            $ref: '#/definitions/eventBody'
        401:
          description: "Unauthorized"
          schema:
            $ref: '#/definitions/UnauthorizedError'
        404:
          description: Event Not Found

definitions:
  eventBody:
      description: "The request parameters for generating a transactional questionnaire link"
      type: "object"
      required:
        - customer
        - channel
        - transaction
      properties:
        type:
          type: "string"
          description: "The event type associated with this link."
          example: "checkout"
        customer:
          type: "object"
          description: "The customer to be invited to leave a review."
          properties:
            firstName:
              type: "string"
              description: "The customer's first name."
              example: "John"
            lastName:
              type: "string"
              description: "The customer's last name."
              example: "Doe"
            email:
              type: "string"
              description: "The customer's email address."
              example: "user@example.com"
            mobile:
              type: "string"
              description: "The customer's mobile phone number."
              example: "+4916286029830"
            address:
              type: "string"
              description: "The customer's address."
              example: "MusterStr. 17, 47110"
            preferredCommunicationChannel:
              type: "string"
              description: "What communication channel is preferred by a customer"
              example: "EMAIL"
              default: "EMAIL"
              enum: ["EMAIL","SMS"]
        channel:
          type: "object"
          description: "The channel which will be associated with the review."
          required:
            - id
          properties:
            id:
              type: "string"
              description: "The unique identifier of the channel."
              example: "my_unique_identifier"
            type:
              type: "string"
              description: "The type of the id used to refer to the channel."
              example: "user_defined"
              default: "etrusted"
              enum: [user_defined, etrusted]
        transaction:
          type: "object"
          description: "The transaction to be reviewed."
          required:
            - reference
          properties:
            reference:
              type: "string"
              description: "An external reference to the transaction."
              example: "ORDER-121416990"
            date:
              type: "string"
              format: "date-time"
              example: "2017-01-01T13:30:15.000Z"
              description: "The date when the transaction occurred."
        system:
          description: "The system name is the technical system name, in which this link will be imbedded. If problem occur, eTrusted will communicate this system name to the integrator for further analysis. Therefore the integrator should use precise names to differentiate his technical systems."
          type: "string"
          example: "customer_system_name"
        systemVersion:
          description: "The system version is the version of the integrator system. This offers organizations the possibility to use different versions of the same integration without putting this information into the system name."
          type: "string"
          example: "1.0"
        metadata:
          type: "object"
          description: "The metadata associated with the review."
  eventPostResponse:
    type: "object"
    properties:
      Message:
        type: "string"
        description: "Response Message. Contains either success or error messages"
        example: "Your event (evt-69d47558-b4e2-11e8-b04a-5153bcba3215) was accepted for processing"
      EventRef:
        type: "string"
        description: "Event Reference"
        example: "evt-69d47558-b4e2-11e8-b04a-5153bcba3215"

  eventPostValidationErrorResponse:
    type: "object"
    properties:
      Message:
        type: "string"
        description: "Error message details"
        example: "Invalid request: instance requires property 'type'"
  UnauthorizedError:
    description: Forbidden
    properties:
      Message:
        type: "string"
        description: "Error message details"
        example: "Forbidden"
