swagger: '2.0'
info:
  title: eTrusted Reviews API
  version: 1.0.0
# NOTE:
# main.md starts with text immediately below h0 with api name, and then contains any other md sections (h1) that will be rendered into separate articles.
  description:
    $ref: "markdown/main.md"
  x-logo:
    url: 'https://cdn-assets-cloud.frontify.com/local/frontify/h_lNxVXLqrDqb2kyrixW3lMmUl7n-aBRzJUzyvzD7_8V50i_9aMpRL54pzZaPLi5Xs2CTNYbJ4nlvLOASdKdZGptMcjDno9EpSa8Iqn_dlwcVKc50LQncMwgSRlMS626?width=2400'
    altText: eTrusted logo
# these are the APIs that should be merged
apis:
- url: 'components/events.yml'
- url: 'components/get-reviews.yml'
- url: 'components/questionnaire-links.yml'
# we need this on highest level
host: api.etrusted.com
schemes:
- "https"
# navigation
tags:
- name: Events
  description:
    $ref: "markdown/intro-events.md"
- name: Get Reviews
  description:
    $ref: "markdown/intro-get-reviews.md"
- name: Questionnaire Link
  description:
    $ref: "markdown/intro-questionnaire-link.md"
